name: Kalkulator CI/CD Pipeline

on:
  push:
    branches: [ main ]
       - develop 
  pull_request:
    branches: [ main ]

jobs:
  integrate-test-inspect:
    name: Integrasi, Tes & Inspeksi
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Kode (Continuous Integration)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Jalankan Tes Unit (Continuous Testing)
        run: |
          echo "Menjalankan tes unit kalkulator..."
          node tests/calculator.test.js

      - name: Setup JDK 17 untuk SonarCloud
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache paket SonarCloud
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Analisis SonarCloud (Continuous Inspection)
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: c0159582f834fc8c1313ae2388f6c825d9920a24
        with:
          projectBaseDir: .
          args: >
            -Dsonar.organization=muhammadgalangpradwita
            -Dsonar.projectKey=MuhammadGalangPradwita_CICD-Kalkulator
            -Dsonar.sources=.
            -Dsonar.host.url=https://sonarcloud.io

  build-docker-image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: integrate-test-inspect

    steps:
      - name: Checkout Kode
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login ke Docker Hub (opsional)
      # - name: Login ke Docker Hub
      #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: local/kalkulator-cicd:latest

  deploy-to-github-pages:
    name: Deploy ke GitHub Pages
    runs-on: ubuntu-latest
    needs: integrate-test-inspect
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: write

    steps:
      - name: Checkout Kode
        uses: actions/checkout@v4

      # Build halaman web (jika diperlukan)
      # - name: Build Halaman Web
      #   run: npm install && npm run build # (atau perintah build yang sesuai)

      - name: Deploy ke GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
